build:
  image: registry.pkgdev.rackspace.com/build-base:ubuntu-16.04
  commands:
    #install build-deps
    - apt-get update
    - echo yes | mk-build-deps --install --remove debian/control
    #set up the upstream branch - has to be orphan so the git archive is pure.
    - export REPO=$(basename $(git rev-parse --show-toplevel))
    - git fetch -t
    - export CHANGELOG_VERSION=$(awk 'NR==1{print $2}' debian/changelog  |tr -d '()')
    - git archive ${CHANGELOG_VERSION} -o ../kthresher_${CHANGELOG_VERSION}.orig.tar.gz
    #execute the build
    - debuild -us -uc
    - cd ..
    - export TIMESTAMP=$(date +%s)
    - ssh drop-point mkdir -p /drop-point/${REPO}/${CHANGELOG_VERSION}
    - scp -r ./*deb drop-point:/drop-point/${REPO}/${CHANGELOG_VERSION}
    - scp -r ./*changes drop-point:/drop-point/${REPO}/${CHANGELOG_VERSION}
    - scp -r ./*dsc drop-point:/drop-point/${REPO}/${CHANGELOG_VERSION}
    - scp -r ./*build drop-point:/drop-point/${REPO}/${CHANGELOG_VERSION}
